name: bondnex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  android_intent_plus: ^5.3.0
  app_usage: ^4.0.1
  call_log: ^6.0.0
  cloud_firestore: ^6.0.0
  cloudinary_public: ^0.23.1
  connectivity_plus: ^6.1.4
  device_preview: ^1.3.1
  file_picker: ^10.2.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.9+2
  flutter_image_compress: ^2.4.0
  google_fonts: ^6.2.1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  local_auth: ^2.3.0
  lottie: ^3.3.1
  lucide_icons: ^0.257.0
  material_design_icons_flutter: ^7.0.7296
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pinput: ^5.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/infinity.json
    - assets/heart.json
    - assets/lock.json
 