// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf4gR5JRFCVJ77i8d0_fIAFo-Kvt1NSc8',
    appId: '1:1098757641748:web:3e2c3003818411b4d1b901',
    messagingSenderId: '1098757641748',
    projectId: 'bondnex-8727f',
    authDomain: 'bondnex-8727f.firebaseapp.com',
    storageBucket: 'bondnex-8727f.firebasestorage.app',
    measurementId: 'G-PZZQ0QBNEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD94ZwTT0SqQ4HueoXHsphKciRVQWC32C4',
    appId: '1:1098757641748:android:8747f7f72bf78e78d1b901',
    messagingSenderId: '1098757641748',
    projectId: 'bondnex-8727f',
    storageBucket: 'bondnex-8727f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnOaFoSQYjJ276-2SKn_GxRdOiXFqxebA',
    appId: '1:1098757641748:ios:7ae037799543b8e0d1b901',
    messagingSenderId: '1098757641748',
    projectId: 'bondnex-8727f',
    storageBucket: 'bondnex-8727f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnOaFoSQYjJ276-2SKn_GxRdOiXFqxebA',
    appId: '1:1098757641748:ios:7ae037799543b8e0d1b901',
    messagingSenderId: '1098757641748',
    projectId: 'bondnex-8727f',
    storageBucket: 'bondnex-8727f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf4gR5JRFCVJ77i8d0_fIAFo-Kvt1NSc8',
    appId: '1:1098757641748:web:13fc3b8441b8b3f8d1b901',
    messagingSenderId: '1098757641748',
    projectId: 'bondnex-8727f',
    authDomain: 'bondnex-8727f.firebaseapp.com',
    storageBucket: 'bondnex-8727f.firebasestorage.app',
    measurementId: 'G-BMGM3K9YYE',
  );
}