// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4krKzVjT0O9-bdnTU8KTHelbcw4Iq5Ew',
    appId: '1:545280202783:android:eab192ca0ce457df4c9d2a',
    messagingSenderId: '545280202783',
    projectId: 'bondnex-0002',
    storageBucket: 'bondnex-0002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKH0fW8qrGdvqmT1QcPbzXdmcjueV76NE',
    appId: '1:545280202783:ios:ed85c4a06115169d4c9d2a',
    messagingSenderId: '545280202783',
    projectId: 'bondnex-0002',
    storageBucket: 'bondnex-0002.firebasestorage.app',
    androidClientId: '545280202783-eul31p3rsok1vcojbe5593fj488mmb08.apps.googleusercontent.com',
    iosClientId: '545280202783-tcrm8csrb836oa8ktqugjn8tsse7fupm.apps.googleusercontent.com',
    iosBundleId: 'com.example.bondnex',
  );
}
